// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entities "github.com/XXena/shorter/internal/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockRecord is a mock of Record interface.
type MockRecord struct {
	ctrl     *gomock.Controller
	recorder *MockRecordMockRecorder
}

// MockRecordMockRecorder is the mock recorder for MockRecord.
type MockRecordMockRecorder struct {
	mock *MockRecord
}

// NewMockRecord creates a new mock instance.
func NewMockRecord(ctrl *gomock.Controller) *MockRecord {
	mock := &MockRecord{ctrl: ctrl}
	mock.recorder = &MockRecordMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecord) EXPECT() *MockRecordMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecord) Create(record entities.Record) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", record)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRecordMockRecorder) Create(record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecord)(nil).Create), record)
}

// Delete mocks base method.
func (m *MockRecord) Delete(recordID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", recordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecordMockRecorder) Delete(recordID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecord)(nil).Delete), recordID)
}

// GetByToken mocks base method.
func (m *MockRecord) GetByToken(token string) (entities.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", token)
	ret0, _ := ret[0].(entities.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockRecordMockRecorder) GetByToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockRecord)(nil).GetByToken), token)
}

// GetByURL mocks base method.
func (m *MockRecord) GetByURL(longURL string) (entities.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByURL", longURL)
	ret0, _ := ret[0].(entities.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByURL indicates an expected call of GetByURL.
func (mr *MockRecordMockRecorder) GetByURL(longURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByURL", reflect.TypeOf((*MockRecord)(nil).GetByURL), longURL)
}

// Update mocks base method.
func (m *MockRecord) Update(recordID int, record entities.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", recordID, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRecordMockRecorder) Update(recordID, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecord)(nil).Update), recordID, record)
}
