// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/service.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entities "github.com/XXena/shorter/internal/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockRecordRepo is a mock of RecordRepo interface.
type MockRecordRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRecordRepoMockRecorder
}

// MockRecordRepoMockRecorder is the mock recorder for MockRecordRepo.
type MockRecordRepoMockRecorder struct {
	mock *MockRecordRepo
}

// NewMockRecordRepo creates a new mock instance.
func NewMockRecordRepo(ctrl *gomock.Controller) *MockRecordRepo {
	mock := &MockRecordRepo{ctrl: ctrl}
	mock.recorder = &MockRecordRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordRepo) EXPECT() *MockRecordRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecordRepo) Create(arg0 entities.Record) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRecordRepoMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecordRepo)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockRecordRepo) Delete(recordID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", recordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecordRepoMockRecorder) Delete(recordID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecordRepo)(nil).Delete), recordID)
}

// GetByURL mocks base method.
func (m *MockRecordRepo) GetByURL(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByURL", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByURL indicates an expected call of GetByURL.
func (mr *MockRecordRepoMockRecorder) GetByURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByURL", reflect.TypeOf((*MockRecordRepo)(nil).GetByURL), arg0)
}

// Redirect mocks base method.
func (m *MockRecordRepo) Redirect(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redirect", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Redirect indicates an expected call of Redirect.
func (mr *MockRecordRepoMockRecorder) Redirect(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redirect", reflect.TypeOf((*MockRecordRepo)(nil).Redirect), arg0)
}

// Update mocks base method.
func (m *MockRecordRepo) Update(recordID int, record entities.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", recordID, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRecordRepoMockRecorder) Update(recordID, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecordRepo)(nil).Update), recordID, record)
}
